CREATE TABLE IF NOT EXISTS raw.faf_shipments (
    fr_orig         TEXT,
    dms_orig        TEXT,
    dms_dest        TEXT,
    fr_dest         TEXT,
    fr_inmode       TEXT,
    dms_mode        TEXT,
    fr_outmode      TEXT,
    sctg2           TEXT,
    trade_type      TEXT,
    dist_band       TEXT,
    tons_2017       NUMERIC,
    tons_2018       NUMERIC,
    tons_2019       NUMERIC,
    tons_2020       NUMERIC,
    tons_2021       NUMERIC,
    tons_2022       NUMERIC,
    tons_2023       NUMERIC,
    tons_2024       NUMERIC,
    tons_2030       NUMERIC,
    tons_2035       NUMERIC,
    tons_2040       NUMERIC,
    tons_2045       NUMERIC,
    tons_2050       NUMERIC,
    value_2017      NUMERIC,
    value_2018      NUMERIC,
    value_2019      NUMERIC,
    value_2020      NUMERIC,
    value_2021      NUMERIC,
    value_2022      NUMERIC,
    value_2023      NUMERIC,
    value_2024      NUMERIC,
    value_2030      NUMERIC,
    value_2035      NUMERIC,
    value_2040      NUMERIC,
    value_2045      NUMERIC,
    value_2050      NUMERIC,
    current_value_2018  NUMERIC,
    current_value_2019  NUMERIC,
    current_value_2020  NUMERIC,
    current_value_2021  NUMERIC,
    current_value_2022  NUMERIC,
    current_value_2023  NUMERIC,
    current_value_2024  NUMERIC,
    tmiles_2017     NUMERIC,
    tmiles_2018     NUMERIC,
    tmiles_2019     NUMERIC,
    tmiles_2020     NUMERIC,
    tmiles_2021     NUMERIC,
    tmiles_2022     NUMERIC,
    tmiles_2023     NUMERIC,
    tmiles_2024     NUMERIC,
    tmiles_2030     NUMERIC,
    tmiles_2035     NUMERIC,
    tmiles_2040     NUMERIC,
    tmiles_2045     NUMERIC,
    tmiles_2050     NUMERIC
);

CREATE TABLE IF NOT EXISTS raw.transborder_freight (
    trdtype         TEXT,
    usastate        TEXT,
    commodity2      TEXT,
    disagmot        TEXT,
    mexstate        TEXT,
    canprov         TEXT,
    country         TEXT,
    value           NUMERIC,
    shipwt          NUMERIC,
    freight_charges NUMERIC,
    df              TEXT,
    contcode        TEXT,
    month           INTEGER,
    year            INTEGER
);

CREATE TABLE IF NOT EXISTS raw.supply_chain_indicators (
    mode            TEXT,
    indicator       TEXT,
    week_number     INTEGER,
    week_ending     TEXT,
    pct_change      NUMERIC
);