freight_flow:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: airflow
      password: airflow
      dbname: freight
      schema: silver
      threads: 4
    docker:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: freight
      schema: silver
      threads: 4
    ci:
      type: postgres
      host: localhost
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: silver
      threads: 4
  target: dev